options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '--platform', 'linux/amd64',
      '-t', 'us-central1-docker.pkg.dev/ncbf2026/cbf-website-repo/fairweb:latest',
      '-f', '/workspace/Dockerfile',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/ncbf2026/cbf-website-repo/fairweb:latest'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'cbf-website',
      '--image', 'us-central1-docker.pkg.dev/ncbf2026/cbf-website-repo/fairweb:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'us-central1-docker.pkg.dev/ncbf2026/cbf-website-repo/fairweb:latest'